(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Clear["Global`*"];


alphabetInteractive = Manipulate[(
	Column[{
		Style[ToString@n <> " Tables", FontSize->20, TextAlignment->Center, Bold],
		ChartGroupsSorted[MakeGroups[n], 600]
	}, Alignment -> Center]), 
	{{ n, 4, "Number of Tables" }, 2, 10, 1 },
	LabelStyle -> { FontSize->14 },
	Initialization:>(
		percents = <|"A"->0.0379425, "B"->0.0850223, "C"->0.077475, "D"->0.0453413, "E"->0.0185658, "F"->0.0338085, "G"->0.0557632, "H"->0.0708041, "I"->0.00413011, "J"->0.0298697, "K"->0.0326326, "L"->0.0491037, "M"->0.0963997, "N"->0.0190822, "O"->0.0152516, "P"->0.0498137, "Q"->0.00241787, "R"->0.0590957, "S"->0.0943162, "T"->0.0354322, "U"->0.00232247, "V"->0.0175313, "W"->0.0554885, "X"->0.000384696, "Y"->0.00634222, "Z"->0.00566274|>;
		percentsInverse = AssociationThread[Values@percents, Keys@percents];	
		ValuesToLetters[list_] := AssociationThread[percentsInverse[#]& /@ list, list];

		SortNewAlphabet[newGroupsN_] := SortBy[Keys[KeySort /@ newGroupsN], First@#&];
		SortLettersByOldAlphabet[newGroups_] := SortBy[KeySort /@ newGroups, First@Keys@#&];
		
		AddOneToSmallestGroup[groups_, remaining_] := (
			sortedByTotal = Reverse@SortBy[groups, Total@#&];
			totals = Total /@ sortedByTotal;
			nextGreatest = First@remaining;
			next = Append[Most@sortedByTotal, Append[Last@sortedByTotal, nextGreatest]];
			index = First@First@Position[remaining, nextGreatest];
			stillStanding = Delete[remaining, index];
			{ next, stillStanding }
		);
		
		MakeGroups[n_] := (
			values = Values@Reverse@Sort[percents];
			groups = List /@ values[[1;;n]];
			remaining = values[[n + 1;;]];
			While[Length@remaining > 0, { groups, remaining } = AddOneToSmallestGroup[groups, remaining]];
			letteredGroups = ValuesToLetters /@ groups
		);
		
		MakeChart[buckets_, sortedAlphabet_, width_] := (
			labeled = Labeled[#, Style[ToString@Round[100. * Total@#, 0.01] <> "%", FontSize->14], After]& /@ buckets;
			BarChart[
			Reverse@labeled,
			BarSpacing->0.2 * 800 / width,
			BarOrigin->Left,
			ChartLayout->"Stacked",
			ChartLabels->Placed[Style[#, RGBColor["#CECECE"], 12]& /@ Flatten@Reverse@Keys@buckets, Center],
			ChartStyle->"Rainbow",
			ImageSize->width,
			PlotRangePadding -> {0, -0.25 * width / 800},
			PlotLabel->Row[
				Framed[
					Style[#, FontSize -> (width / 800) * 24, Black, Bold],
						FrameMargins->4,
						Background->White,
						ImageMargins->{{0,-1},{10,0}}
					]& /@ (StringRiffle[#, ","]& /@ sortedAlphabet)
				]
			]
		);
		
		ChartGroupsSorted[newGroups_, width_:800] := (
			sortedNewGroups = SortLettersByOldAlphabet[newGroups];
			sortedAlphabet = SortNewAlphabet[newGroups];
			MakeChart[sortedNewGroups, sortedAlphabet, width]
		)
	)
]


CloudDeploy[alphabetInteractive, Permissions->"Public"]
